apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopssquad5
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devopssquad5
  template:
    metadata:
      labels:
        app: devopssquad5
    spec:
      containers:
      - name: devopssquad5
        image: aryandoescode/maven-build:latest
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: devopssquad5-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: devopssquad5
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: devopssquad5-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devopssquad5
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 50
